language: node_js
node_js:
  - 6
  - 7
  - 8
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgif-dev
before_install:
  - npm i -g npm@5.2.0
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run cover
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: bot_upload
  skip_cleanup: true
  on:
    node: '6'
  bucket: discordbot-builds
  region: us-east-1
script:
  - zip -r latest *
  - mkdir -p bot_upload
  - mv latest.zip bot_upload/latest.zip
notifications:
  discord:
    channels:
      - $DISCORD_WEBHOOK_ID:$DISCORD_WEBHOOK_TOKEN
    pull_request_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} in PR [#%{pull_request_number}](%{pull_request_url}) by %{author} %{result} in %{duration}'
    branch_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} by %{author} %{result} in %{duration}'
