language: node_js
node_js:
  - 6
  - 7
  - 8
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgif-dev
before_install:
  - npm i -g npm@5.3.0
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run cover
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: bot_upload
  skip_cleanup: true
  on:
    node: '8'
  bucket: discordbot-builds
  region: us-east-1
script:
  - zip -r latest * -x node_modules/\*
  - mkdir -p bot_upload
  - mv latest.zip bot_upload/latest.zip
after_failure:
  - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"Build has failed!"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN
after_success:
  - test $TRAVIS_NODE_VERSION = '8' && curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"Build successfully built!"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN
notifications:
  email: false
