language: node_js
node_js:
  - 6
  - 7
  - 8
before_install:
  - npm i -g npm@5.0.4
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run cover
