version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=*,-not_this
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
